apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-record-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-record-frontend
  template:
    metadata:
      labels:
        app: student-record-frontend
    spec:
      containers:
      - name: frontend
        image: your-dockerhub-username/student-record-frontend:latest
        ports:
          - containerPort: 3000
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://backend-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: student-record-frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
