apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-record-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-record-backend
  template:
    metadata:
      labels:
        app: student-record-backend
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/student-record-backend:latest
        ports:
          - containerPort: 5000
        env:
          - name: MONGO_URI
            value: "mongodb://mongo-service:27017/studentdb"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: student-record-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
